host_dir: "/Users/nakamurasatoru/git/d_shibusawa/lab1/docs"
app_dir: "/Users/nakamurasatoru/git/d_shibusawa/app1/static"
host_url: "https://shibusawa-dlab.github.io/lab1"
app_url: "https://shibusawa-dlab.github.io/app1"
algolia_index: "main"
date: "20210402"